### ISSUE TITLE
Депутат Яручик. Невірно фракція

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lutsk#1]
в депутатів [на цій сторінці](http://www.lutskrada.gov.ua/deputy?field_person_district_tid=All&field_person_faction_tid=All&page=2) біля фото вказано фракцію. В нього нічого не вказано, тому він позафракційний. 

![image](https://user-images.githubusercontent.com/14181306/28661364-16aa44da-72bf-11e7-8471-52b3d38e711d.png)

**Comment by beastie87** [comment]
@lisoffsky  thank you!
Fix  done! https://lutsk.rada4you.org/people?filter=Позафракційний&amp;sort=faction
